      - name: Prepare Pages artifact
        run: |
          mkdir -p public
          cp out/podcast.xml public/
          # (Optional) also copy public/cover.jpg if you add artwork

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
